### ISSUE TITLE
[Needs fix] Re-instantiate Phoenix.rebirth() after language/region change

### ISSUE THREAD

**Issue by Flunzmas** [Flunzmas/seasoncalendar#101]
**Describe the bug**
When sorting foods by name alone after having changed the language, they're sorted by the old locale's names.

* => use rebirth again to simply restart App after change. That way, all locale/region-dependent widgets are filled properly.

**To Reproduce**
1. Change language
2. Disable food sorting by availability
3. Have a look at the foodView. The foods are sorted by the names of the old language.

**Expected behavior**
Sorting by the current language

**Comment by matzebond** [comment]
Note:
Phoenix is no longer needed was removed because AppConfig and AppData can rebuild the App on demand.
Whether this is more efficient remains questionable but at least it's a dependency less :sweat_smile:
