### ISSUE TITLE
 european countries food availability

### ISSUE THREAD

**Issue by akaessens** [Flunzmas/seasoncalendar#104]
Probably belongs to #47 

Here is the overview for all of Europe with national sources linked: https://www.eufic.org/en/explore-seasonal-fruit-and-vegetables-in-europe

Hope it is helpful

**Comment by Flunzmas** [comment]
That's a really nice list, will check it out in a few weeks when my schedule allows it again :)

**Comment by matzebond** [comment]
Thanks for the hint this will be continued in #47
