### ISSUE TITLE
New (language) release and/or extra maintainers

### ISSUE THREAD

**Issue by PanderMusubi** [Flunzmas/seasoncalendar#107]
This is a very useful app for a more sustainable world with a lot of contributions from the community. Would be a loss if no longer new releases would be made.

I had a Dutch translation laying around from two years ago with which I just have completed the Dutch translation in Weblate. See also https://github.com/Flunzmas/seasoncalendar/pull/106

According to Weblate, there are also more translations available then in the last release of this app. Making a release with only additional language support would easily bring those translation to the end users.

Perhaps @dfuchss , @matzebond or @comradekingu could so a release for at least F-Droid?

PS The empty Dutch translation for Belgium in Weblate can be deleted. The `nl` serves both the Netherlands and Belgium.

**Comment by comradekingu** [comment]
Unfortunately this project has imposed a CoC, so I'm out.

**Comment by PanderMusubi** [comment]
Respect for your decision. Hope to see continuity by the others. :smiley:

**Comment by matzebond** [comment]
Thank you very much for the dutch translation. I will try to get a new release to f-droid.

**Comment by matzebond** [comment]
1.4.8 was just released in f-droid.
Thanks again for the translation!
