### ISSUE TITLE
The Wikipedia button is not really aligned/centered

### ISSUE THREAD

**Issue by Altonss** [Flunzmas/seasoncalendar#112]
**Describe the bug**
The Wikipedia button is not really aligned/centered. This is more of a small visual bug, as for me the wikipedia button seems a little bit wrongly placed.

**To Reproduce**
1. Go to a element of the list (fruit or vegetable)
2. Click onthis element
3. Scroll down to the Wikipedia and back buttons

**Expected behavior**
The 2 buttons should be better aligned (especially the Wikipedia one). But this is just a minor detail!

**Screenshots**
![Screenshot_2022-01-28-00-27-53](https://user-images.githubusercontent.com/66519591/151508616-7488562f-b0a1-451f-b528-65a2971c7a69.png)

**Used device (please complete the following information):**
 - Device: Samsung Galaxy Core Prime
 - OS: Android 5.0.1
 - Browser: Fennec F-Droid
 - App Version: 1.4.8+43(f)

**Comment by matzebond** [comment]
This behavior follows the material design guidelines for [dialogs](https://material.io/components/dialogs). 
We are [using](https://github.com/Flunzmas/seasoncalendar/blob/a66501a49d144d7d4213347a7f7f971b9a3bb50b/lib/components/food_tile.dart#L118) the defaults for flutters [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html).

For #102 the dialog will have to be redesigned anyway. Hopefully the layout will be more pleasing ;-)
