### ISSUE TITLE
Impossible to add an element to the favorites

### ISSUE THREAD

**Issue by Altonss** [Flunzmas/seasoncalendar#113]
**Describe the bug**
Impossible to add an element to the favorites

**To Reproduce**
1. Go to an element (fruit or vegetable)
2. Click on the star to mark it as favorite
3. See error: nothing happens

**Expected behavior**
The element should be a favorite now!

**Used device (please complete the following information):**
 - Device: Samsung Galaxy Core Prime
 - OS: Android 5.0.1
 - Browser: Fennec F-Droid
 - App Version: 1.4.8+43(f)

**Comment by matzebond** [comment]
Thanks for reporting this.

**Comment by Altonss** [comment]
Thank you for the app ! :smile:
