### ISSUE TITLE
Should distinguish Chicory (sprout) from Chicory (salad) 

### ISSUE THREAD

**Issue by goebbe** [Flunzmas/seasoncalendar#117]
Chicory has two common forms that are available in shops and that differ largely with respect to cultivation time and availability:
The app should distinguish between its form as:  
1. Salad (Chichorium_endivia/ ger: Endivie-Salat) 
2. Sprout (eng: Chicory / ger:  Chicorée)  

Botanically, it is the same plant! 

But the salad grows in late summer (in Europe) while the sprout is freshly available (locally) almost the whole year.  The sprouts do not need sunlight to grow. 

Currently, the App (in German) only shows Chicorée (the term used for the sprout) - but shows a picture of the salad)  
I recommend distinguishing between the two forms and use appropriate pictures. (e.g. from Wikipedia)

Here are links to the Wiki artikles describing the differences (and providing pictures)
https://en.wikipedia.org/wiki/Chicory#Cultivated
(https://de.wikipedia.org/wiki/Chicor%C3%A9e)

https://en.wikipedia.org/wiki/Cichorium_endivia
https://de.wikipedia.org/wiki/Endivie

Thank you for this great app!

**Comment by matzebond** [comment]
We have both entries in the app Chicory/Chiorée and Endive/Endivie but they are erroneous. 
I guess a better image for Chicory would be https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Endivie.jpg (name Endivie?) would be better. Is the availability data also mix up? I remember the Endivie as a winter salad.

**Comment by goebbe** [comment]
Harvest time for Endivia (salad): August - November
Source: https://www.mein-schoener-garten.de/pflanzen/gemuse/endivie-friseesalat

The suggested picture on wiki would be good choice for the Chicory entry.  

Chicory and Endivia are the same plant - so there will always be confusion about the different names. 
However, there are two very distinct ways to cultivate and harvest the plant. 

If there is already a separate entry for Endiva/Endivie, then it is probably sufficient to change the picture of the Chicory entry. 
Thanks for taking the time, to comment.
