### ISSUE TITLE
Intuitive handling of the buttons to select fruit or vegetables

### ISSUE THREAD

**Issue by dfuchss** [Flunzmas/seasoncalendar#26]
I got slightly confused about how to use the buttons to select fruit or vegetables.

The following state transitions (bold print confuses me):

**Fruit | Vege --- Fruit ---> Fruit | !Vege** (1)
**Fruit | Vege --- Vege ---> !Fruit | Vege** (1)

**Fruit | !Vege --- Fruit ---> Fruit | Vege** (2)
Fruit | !Vege --- Vege --->Fruit | Vege

!Fruit | Vege --- Fruit --->  Fruit | Vege
**!Fruit | Vege --- Vege --->  Fruit | Vege** (2)

(1): quite strange :)
(2): understandable, but would not allow a transition, because that would be more intuitive from my point of view

**Comment by Flunzmas** [comment]
> I got slightly confused about how to use the buttons to select fruit or vegetables.
> 
> The following state transitions (bold print confuses me):
> ...

The current transitions are the most intuitive I was able to come up when I implemented the buttons. If you have a suggestion that we both find more intuitive, I will change it :).

**Comment by dfuchss** [comment]
I would prefer:
ad (1): Just disable Fruit when clicking on "active fruit" (and vice versa for vegetables)

ad (2): show no fruits / vegetables when disabling both (show some empty set / see #10 ) or just disable behavior of enabling the other one (in other words: on click do nothing :) ) 

What's your opinion on that?

**Comment by Flunzmas** [comment]
Now, that nobody else seems to find it unintuitive that way, I'll close this issue (will repoen it when there's the need to talk about this again :grin: ).
