### ISSUE TITLE
Fastlane: misnamed directory

### ISSUE THREAD

**Issue by IzzySoft** [Flunzmas/seasoncalendar#33]
I wonder why my updater never manages to pick the changelog… Could you please rename `en-us` to `en-US`? Language is lower-case, but variant upper-case. If I missed something and it's case insensitive, I stand corrected – but everywhere else that's what I see. References:

* [my Fastlane snippet](https://gitlab.com/snippets/1895688)
* [F-Droid's docu on it](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure)
* [official Fastlane docu](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new)

Thanks!

**Comment by Flunzmas** [comment]
I somehow assumed that naming them according to the ISO 639-1 standard was correct... will fix this very soon!

**Comment by IzzySoft** [comment]
I'd assume Fastlane was basing this on existing norms, yes. But does ISO 639-1 cover language variants? If I understood correctly, it only covers the first part (here: `en`), which is the language – not the second part (`US`) for the locale, which is covered by ISO 3166 (and indeed uppercase, see e.g. [Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)).

Thanks for fixing!
