### ISSUE TITLE
[Feature-request] Option to set specific language

### ISSUE THREAD

**Issue by revuwa** [Flunzmas/seasoncalendar#40]
Thank you so much for [multi-language-support](https://github.com/Flunzmas/seasoncalendar/issues/17) and for adding more and more [languages](https://github.com/Flunzmas/seasoncalendar/issues/36).

For me, and possibly for other people it would be useful to be able to set a specific language inside the app.
Some people using another Android language. E. g. using English Android system language for some reasons, but want to use some apps in other languages, like yours in the native German one.

It would be pretty cool to see some option for that in some future releases.
What do you think?

**Comment by Flunzmas** [comment]
I like the idea!

When implementing multi-lang support I also thought about an option to manually set the app's language, but ended up postponing that as most people would probably be fine with using the language of their device (and unfortunately I can't put that much time into this right now as it's a leisure project).

 I'll have a look at this in the following weeks if I find the time.

**Comment by revuwa** [comment]
I just wanted to thank you for the fast and excellent working implementation ♥
