### ISSUE TITLE
Search doesn't find all

### ISSUE THREAD

**Issue by Alex-Esko** [Flunzmas/seasoncalendar#46]
Hi,
nice App your wrote. The pictures make it particularly cute.
I found it in the [IzzyOnDroid](https://android.izzysoft.de/repo) repository. Hope to see it in the wider used F-Droid repo soon.

v1.4.0+31
When searching for "Zwiebel" only one of two results is shown, respectively for "Zwiebeln".
Searching for "zwi" turns up Kiwi and "ere" Erbsen.

Regards,
Alexander

![Screenshot_20201110-132304](https://user-images.githubusercontent.com/5099066/98674065-8deac680-2358-11eb-83ee-1f2aec78e469.png)
![Screenshot_20201110-132716](https://user-images.githubusercontent.com/5099066/98674069-904d2080-2358-11eb-8be3-a059aac2c1ee.png)

**Comment by Flunzmas** [comment]
Thanks for letting me know and glad you like it! F-Droid repo presence is coming as soon as the packagers pick it up from my request :grin: 

A well-working search function is a piece of art, so I currently help myself with a fuzzy search over all food names and synonyms. If no exact name match is found, all foods with a "similar" name/synonym are shown (this is why "Zwi" results in "Kiwi", as you can get the latter relatively easy by replacing "Z" by "Ki").

the "Zwiebel" thing though was just a misnaming issue. I fixed it, and the corrected names will ship with v1.4.1 in 2-3 weeks!

Optimizing the search function is something to note, but currently I'd like to implement other features first. For now, I think it's okay for most people to see a wider range of similar foods than to not display anything when the search query is not perfectly matching a food :grin:
