### ISSUE TITLE
Enable user to locally adjust availability data

### ISSUE THREAD

**Issue by Flunzmas** [Flunzmas/seasoncalendar#54]
**Impl.:** e.g. a button "Adjust availability" in the foodInfo Dialog from which the user can select the availability per month.
**Technical:** needs implementation of write-access to asset db.
**Problem:** How to keep locally overwritten data if a version updates also changes the DB's data?

**Comment by matzebond** [comment]
This might be a good first step towards a _collaborative availability database_ where every user can edit availability data Wikipedia style.

>  Problem: How to keep locally overwritten data if a version updates also changes the DB's data?

Probably just assume the user is more accurate than our data and keep using the users data. This would require item wise adjustable availability by the user.

**Comment by dfuchss** [comment]
@Flunzmas consider a second db that contains the overrides for some availability. This would make it easy to update the database from your side. Furthermore, the main db wouldn't be "destroyed".

**Comment by Flunzmas** [comment]
> @Flunzmas consider a second db that contains the overrides for some availability. This would make it easy to update the database from your side. Furthermore, the main db wouldn't be "destroyed".

Nice Idea!



> This might be a good first step towards a _collaborative availability database_ where every user can edit availability data Wikipedia style.

In your vision, would this be still available from this repo or hosted on a dedicated server?

**Comment by matzebond** [comment]
A dedicated server would be the quicker way of getting my regional improvements to my friends who also us this app. But maybe such a solution would be over engineered and a simple export functionality is enough for sharing with friends and the community. 

Edit: The export functionality would also work nice with the two dbs approach.

**Comment by dfuchss** [comment]
DB Part should be implemented in `user_db_provider.dart` .

**Comment by Flunzmas** [comment]
Update: Seems to be implemented, now it only needs to be tested.
