### ISSUE TITLE
fdroiddata: merge request with the generated yml?

### ISSUE THREAD

**Issue by Flunzmas** [Flunzmas/seasoncalendar#60]
Check whether we can get the app to F-Droid using this path.

As suggested here: https://gitlab.com/fdroid/rfp/-/issues/1496

**Comment by matzebond** [comment]
MR is in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7981

Currently the build fails with some reference to `git submodule`?

**Comment by licaon-kter** [comment]
Close this
