### ISSUE TITLE
Investigate and Reduce app size

### ISSUE THREAD

**Issue by matzebond** [Flunzmas/seasoncalendar#64]
> Mobile app file size is important. If your mobile app is too large, it may be difficult or expensive for users to download. A lengthy ‘time to first play’ could turn users off before they even experience your mobile app. And a user’s device may have an extremely small amount of disk space.

The app currently stands at ~30mb average size for Android apps in 2017 was 11mb.
I don't know if that is to be expected for a flutter app but maybe some investigation into the biggest dependencies is worth the time
https://flutter.dev/docs/development/tools/devtools/app-size

And I guess the lack of tracking libraries also favors our app in size comparison with some other apps :-)

**Comment by IzzySoft** [comment]
Funny crossing, I just wrote that in a mail to Andy. So OK, here comes what "blows it up" and what can be done to "shrink it down". Even to those 11M, though you most likely don't want to go that far.

**Images**

All those nice apples, oranges etc. sum up to a little over 10M currently. Apply the following actions to them half the size (actually 5.3M):

* remove all Exif
* compress JPGs to quality=75

This is a quite good compromise I use on eBooks for years now. Mobile users won't note the difference (just the one in size). Images are for illustration here, not to make an artwork gallery :wink:

**Database**

Not much, but again you can half the size and save 100k by running `VACUUM;` before committing it to git.

**The BigBugBunny**

… has a name: Flutter. A big disadvantage with Flutter is that each app must ship the Flutter libraries for each architecture it shall support. That's around 15M per arch with your app (unpacked). You've got 3 archs here. No chance to reduce this one (except for removing dependencies, maybe).

**Result:**

A single-arch APK for armeabi-v7 with above actions applied on will be 11.5M. I didn't check the multi-arch size, but that will then be around 22..25M I guess. Reducing dependencies might help shrinking the Flutter libs; I've no experience with that.

**Comment by Flunzmas** [comment]
Alright, so the images have been compressed to quality=70 and the DB was vacuumed, solving the issue for now (won't look at the dependencies right now).

For the future, a build script doing some preparatory work (e.g. the vacuuming) before building all the different application files (aab/apk, different architectures) would be cool.

**Comment by IzzySoft** [comment]
Dependency check is a different (and continuing/repeating) task – it's always good to get rid of "ballast" not needed. Thanks for tackling the "easy part" for now (the one with the best effort-to-restult ratio) – and agreed, automating this "pre-build" is a good idea :smiley:
