### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Flunzmas/seasoncalendar#68]
Ref: https://f-droid.org/wiki/index.php?title=flunzmas.seasoncalendar/lastbuild_39&oldid=285497

**Comment by matzebond** [comment]
Any idea where this problem could be rooted?
Why doesn't the [pipeline](https://gitlab.com/maschm/fdroiddata/-/jobs/937760970) with `fdroid build` raise a similar error?

I guess we could try removing gradle from the build process, but last I tried I got other errors...

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8120

ref: https://gitlab.com/fdroid/fdroidserver/-/issues/743

**Comment by matzebond** [comment]
thank you very much!
