### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by Flunzmas** [Flunzmas/seasoncalendar#7]
- move building blocks to their own dart files
- restructure packages

**Comment by dfuchss** [comment]
* also consider renaming `com.example.seasoncalendar` to something like `com.flunzmas.seasoncaledar` in android / ios

**Comment by dfuchss** [comment]
You may provide a formatter or something else for collaboration :)

**Comment by Flunzmas** [comment]
> You may provide a formatter or something else for collaboration :)

The project's dart files are now formatted using `dartfmt`
