### ISSUE TITLE
add region info to App description and About/HowTo section

### ISSUE THREAD

**Issue by nylki** [Flunzmas/seasoncalendar#75]
I just discovered your app and love most things about it, well done!

One thing that i am missing is the info which region the apps data is currently based on.
I discovered it to be Central Europe on the git repo here, but this info is not present inside the app itself.

As long as there is no multi-region support yet, I suggest adding a sentence about the data source and region, in the howto-page or the about-page.

**Comment by Flunzmas** [comment]
Yep, totally right.

I forgot F-Droid would publish to the whole world and thus made the app available to people outside central Europe before having suitable data for them :)

**Comment by mannp** [comment]
Agree, love the app, thought wow a UK version too, until I saw the central Europe ref here 😃

**Comment by Flunzmas** [comment]
Update: Now that the whole world is able to download the app, they should at least see a mention in the app description as well stating that we cover only central Europe so far :).
