### ISSUE TITLE
Seasons for which part of the world?

### ISSUE THREAD

**Issue by kozross** [Flunzmas/seasoncalendar#78]
What part of the world does this app assume for seasonality? I'm from New Zealand, and the information from the app definitely doesn't align with our seasons.

**Comment by tim-hub** [comment]
Just want to create a similar issue too.

It is better to add a feature to allow users to select their own location. At least South or North.😀

**Comment by tim-hub** [comment]
But u like the idea of the app.

**Comment by kozross** [comment]
Honestly, it should be geographically-specific by country. The app lists avocadoes in _New Zealand_ as 'imported all year round'. Hint: we grow avocadoes, and the Hass variety was developed here.

**Comment by Flunzmas** [comment]
Wow, I totally underestimated how quickly people from all over the world would pick up the app... thanks for the feedback!
Current data is for central Europe only, and thus it definitely is off for e.g. the southern Pacific.

It's definitely necessary to extend the regions offered (#47) or at least enable users to locally change the data (#54), but currently I sadly don't know where to get the Data. So if you happen to have open-source availability data for your region and would like to have it integrated, I'd gladly do that job :smile:.

**Comment by kozross** [comment]
As a stopgap measure, it might be worth stating this fact (that it's regioned to central Europe only) clearly in the app description.

**Comment by Flunzmas** [comment]
Yep, that's definitely coming ASAP (see #75).
