### ISSUE TITLE
Wrong French translation of the word "availability"

### ISSUE THREAD

**Issue by bmassot** [Flunzmas/seasoncalendar#89]
In 3 translation French keys, the world "availability" is translated as "saison", which is just wrong and misleading. Please correct as follows:
- imprintPageDataHeadline: Données de disponibilité
- settingsFilterTitle: Filtrer par disponibilité
- settingsSortingTitle: Trier par disponibilité

**Comment by Flunzmas** [comment]
Has been corrected and pushed and will be in the app's next version.

Thanks for the notice, I'm no native speaker :)
