### ISSUE TITLE
[Needs fix] No clear indication of which region is supported

### ISSUE THREAD

**Issue by jpaugh** [Flunzmas/seasoncalendar#91]
## I can't tell whether the app supports my region, or somewhere nearby

The app does not provide any indication that it does not support my region; but since it doesn't ask for location, I know it must be wrong. If I knew the region that the database was.developed for, I would know whether I could rely on it or not.

For example, since I live in the Midwest of USA, I could reasonably use the app if it were regional to any US state (mentally substituting 🚛 instead of 🏠).

If it's somewhere in Europe, then I imagine a great many Europeans could do the same mental juggling, and I would know to look elsewhere.

## To Reproduce
1. Find app on F-Droid.
2. Read app summary.
3. Download and install.

## Related Issues
This is related to #47, but far easier to fix! 😁

**Comment by Flunzmas** [comment]
Hey there,

With the latest version (1.4.7) I have added a bullet point to the app's description as this indeed threw off some people: 

> * Data presets currently available: Central Europe

In case you are referring to version 1.4.7, this means I might have to state it more clearly :grin:
