### ISSUE TITLE
Lang. Settings screen: Show beta notice for incomplete translations

### ISSUE THREAD

**Issue by matzebond** [Flunzmas/seasoncalendar#94]
Languages that are only 7% translated are not that helpful, maybe don't show them in the interface.

Even better (?) show percent of translation for all language options and also link to weblate for easy contribution.

**Comment by Flunzmas** [comment]
Update: All languages that have arb files and are registered in the code can now be chosen in the language settings. Missing translations are filled up with the english translations.

For those incomplete translations, we should indicate in the language settings menu that they're still incomplete.
